version: "3.3"
services:
  back-empresa:
    container_name: back-empresa
    build: .
    ports:
      - 8090:8090
    networks:
      - mynetwork
    environment:
      EUREKA_HOST: http://eureka:8761/eureka

  mongo:
    image: mongo
    ports:
      - 9001:27017
    networks:
      - mynetwork
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=Dds9cP4zlMMIEgGQ
    volumes:
      - mongo-data:/data/db
networks:
  mynetwork:
    external: true
volumes:
  mongo-data:
