version: "3.3"
services:
  empresa:
    build: .
    ports:
      - '8090:8090'
    links:
      - mongo_container
  mongo_container:
    image: mongo
    ports:
      - '9001:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=Dds9cP4zlMMIEgGQ
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: