version: "3.3"
services:
  zookeeper-empresa:
    container_name: zookeeper-empresa
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22182:2181
    networks:
      - mynetwork

  kafka-empresa:
    container_name: kafka-empresa
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-empresa
    ports:
#      - 9092:9092
      - 29093:29092
    networks:
      - mynetwork
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-empresa:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-empresa:9092,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  back-empresa:
    container_name: back-empresa
    build: .
    ports:
      - 8090:8090
    networks:
      - mynetwork
    environment:
      EUREKA_HOST: http://eureka:8761/eureka
      KAFKA_CONSUMER_HOST: http://kafka:9092
      KAFKA_PRODUCER_HOST: http://kafka:9092

  mongo:
    container_name: mongodb-empresa
    image: mongo
    ports:
      - 9001:27017
    networks:
      - mynetwork
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=Dds9cP4zlMMIEgGQ
    volumes:
      - mongo-data:/data/db
networks:
  mynetwork:
    external: true
volumes:
  mongo-data:
