version: "3.3"
services:
  web:
    build: .
    ports:
      - '8000:8000'
      - '8001:8001'
    links:
      - mongo_container
  mongo_container:
    image: mongo
    ports:
      - '9000:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=Dds9cP4zlMMIEgGQ
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    links:
#      - zookeeper
#    ports:
#      - '29092:29092'
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#  zookeeper:
#    image: confluentinc/cp-zookeeper:5.3.0
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SYNC_LIMIT: 2
#    ports:
#      - 2181:2181
#    volumes:
#      - zk-data:/var/lib/zookeeper/data
#      - zk-txn-logs:/var/lib/zookeeper/log
#  kafka:
#    image: confluentinc/cp-kafka:5.3.0
#    container_name: kafka
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_BROKER_ID: 2
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    ports:
#      - 9092:9092
#    volumes:
#      - kafka-data:/var/lib/kafka/data
#volumes:
#  zk-data:
#  zk-txn-logs:
#  kafka-data:

